
-- 직원 테이블
create table employee(
                         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                         EMPLOY_ID INT NOT NULL,
                         EMPLOY_NAME VARCHAR(50) NOT NULL,
                         DEPARTMENT VARCHAR,
                         EMPLOY_RANK VARCHAR(50) NOT NULL,
                         PHONE VARCHAR(20),
                         EMAIL VARCHAR(30),
                         CREATE_AT TIMESTAMP,
                         MODIFY_AT TIMESTAMP
);
-- 파일 테이블
CREATE TABLE file(
                     ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     EMPLOY_ID INT NOT NULL,
                     ORIGINAL_NAME VARCHAR NOT NULL,
                     SAVE_NAME VARCHAR NOT NULL,
                     SAVE_PATH VARCHAR,
                     CREATE_AT TIMESTAMP,
                     CONSTRAINT fk_employee_file FOREIGN KEY (EMPLOY_ID)
                         REFERENCES EMPLOYEE (ID)
                         ON DELETE CASCADE
);
--이메일 기록 테이블
CREATE TABLE EMAIL_HISTORY (
                               ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                               EMPLOY_ID BIGINT NOT NULL,
                               EMAIL VARCHAR(255) NOT NULL,
                               SEND_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               FOREIGN KEY (EMPLOY_ID) REFERENCES employee(id) ON DELETE CASCADE

);

--태스트 데이터
INSERT INTO employee (EMPLOY_ID, EMPLOY_NAME, DEPARTMENT, EMPLOY_RANK, PHONE, EMAIL, CREATE_AT, MODIFY_AT) VALUES
                                                                                                               (1, '김철수', '개발팀', '인턴', '010-1234-5678', 'chulsu.kim@example.com', '2024-07-01 10:00:00', '2024-07-01 10:00:00'),
                                                                                                               (2, '박영희', '경영지원팀', '사원', '010-2345-6789', 'younghee.park@example.com', '2024-07-01 11:00:00', '2024-07-01 11:00:00'),
                                                                                                               (3, '이민수', '영업팀', '주임', '010-3456-7890', 'minsu.lee@example.com', '2024-07-01 12:00:00', '2024-07-01 12:00:00'),
                                                                                                               (4, '최미라', '디자인팀', '대리', '010-4567-8901', 'mira.choi@example.com', '2024-07-01 13:00:00', '2024-07-01 13:00:00'),
                                                                                                               (5, '정승환', '마케팅팀', '부장', '010-5678-9012', 'seunghwan.jeong@example.com', '2024-07-01 14:00:00', '2024-07-01 14:00:00'),
                                                                                                               (6, '강하늘', '회계팀', '차장', '010-6789-0123', 'haneul.kang@example.com', '2024-07-01 15:00:00', '2024-07-01 15:00:00'),
                                                                                                               (7, '윤소희', '개발팀', '이사', '010-7890-1234', 'sohee.yoon@example.com', '2024-07-01 16:00:00', '2024-07-01 16:00:00'),
                                                                                                               (8, '장민호', '경영지원팀', '인턴', '010-8901-2345', 'minho.jang@example.com', '2024-07-01 17:00:00', '2024-07-01 17:00:00'),
                                                                                                               (9, '백지훈', '영업팀', '사원', '010-9012-3456', 'jihun.baek@example.com', '2024-07-01 18:00:00', '2024-07-01 18:00:00'),
                                                                                                               (10, '한지민', '디자인팀', '주임', '010-0123-4567', 'jimin.han@example.com', '2024-07-01 19:00:00', '2024-07-01 19:00:00'),
                                                                                                               (11, '서지수', '마케팅팀', '대리', '010-1234-5679', 'jisu.seo@example.com', '2024-07-01 20:00:00', '2024-07-01 20:00:00'),
                                                                                                               (12, '권태현', '회계팀', '부장', '010-2345-6780', 'taehyun.kwon@example.com', '2024-07-01 21:00:00', '2024-07-01 21:00:00'),
                                                                                                               (13, '김민준', '개발팀', '차장', '010-3456-7891', 'minjun.kim@example.com', '2024-07-01 22:00:00', '2024-07-01 22:00:00'),
                                                                                                               (14, '이하늘', '경영지원팀', '이사', '010-4567-8902', 'haneul.lee@example.com', '2024-07-01 23:00:00', '2024-07-01 23:00:00'),
                                                                                                               (15, '박하린', '영업팀', '인턴', '010-5678-9013', 'harin.park@example.com', '2024-07-02 00:00:00', '2024-07-02 00:00:00'),
                                                                                                               (16, '송하나', '디자인팀', '사원', '010-6789-0124', 'hana.song@example.com', '2024-07-02 01:00:00', '2024-07-02 01:00:00'),
                                                                                                               (17, '정윤호', '마케팅팀', '주임', '010-7890-1235', 'yunho.jeong@example.com', '2024-07-02 02:00:00', '2024-07-02 02:00:00'),
                                                                                                               (18, '강유진', '회계팀', '대리', '010-8901-2346', 'yujin.kang@example.com', '2024-07-02 03:00:00', '2024-07-02 03:00:00'),
                                                                                                               (19, '이세영', '개발팀', '부장', '010-9012-3457', 'seyoung.lee@example.com', '2024-07-02 04:00:00', '2024-07-02 04:00:00'),
                                                                                                               (20, '한지원', '경영지원팀', '차장', '010-0123-4568', 'jiwon.han@example.com', '2024-07-02 05:00:00', '2024-07-02 05:00:00'),
                                                                                                               (21, '박도영', '영업팀', '이사', '010-1234-5670', 'doyoung.park@example.com', '2024-07-02 06:00:00', '2024-07-02 06:00:00'),
                                                                                                               (22, '유정훈', '디자인팀', '인턴', '010-2345-6781', 'junghoon.yoo@example.com', '2024-07-02 07:00:00', '2024-07-02 07:00:00'),
                                                                                                               (23, '김수아', '마케팅팀', '사원', '010-3456-7892', 'sua.kim@example.com', '2024-07-02 08:00:00', '2024-07-02 08:00:00'),
                                                                                                               (24, '이상민', '회계팀', '주임', '010-4567-8903', 'sangmin.lee@example.com', '2024-07-02 09:00:00', '2024-07-02 09:00:00'),
                                                                                                               (25, '최다은', '개발팀', '대리', '010-5678-9014', 'daeun.choi@example.com', '2024-07-02 10:00:00', '2024-07-02 10:00:00'),
                                                                                                               (26, '윤지원', '경영지원팀', '부장', '010-6789-0125', 'jiwon.yoon@example.com', '2024-07-02 11:00:00', '2024-07-02 11:00:00'),
                                                                                                               (27, '배유나', '영업팀', '차장', '010-7890-1236', 'yuna.bae@example.com', '2024-07-02 12:00:00', '2024-07-02 12:00:00'),
                                                                                                               (28, '장민지', '디자인팀', '이사', '010-8901-2347', 'minji.jang@example.com', '2024-07-02 13:00:00', '2024-07-02 13:00:00'),
                                                                                                               (29, '박하영', '마케팅팀', '인턴', '010-9012-3458', 'hayoung.park@example.com', '2024-07-02 14:00:00', '2024-07-02 14:00:00'),
                                                                                                               (30, '홍지수', '회계팀', '사원', '010-0123-4569', 'jisu.hong@example.com', '2024-07-02 15:00:00', '2024-07-02 15:00:00');