
-- 직원 테이블
create table employee(
                         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                         EMPLOY_ID INT NOT NULL,
                         EMPLOY_NAME VARCHAR(50) NOT NULL,
                         DEPARTMENT VARCHAR,
                         EMPLOY_RANK VARCHAR(50) NOT NULL,
                         PHONE VARCHAR(20),
                         EMAIL VARCHAR(30),
                         CREATE_AT TIMESTAMP,
                         MODIFY_AT TIMESTAMP
);
-- 파일 테이블
CREATE TABLE file(
                     ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     EMPLOY_ID INT NOT NULL,
                     ORIGINAL_NAME VARCHAR NOT NULL,
                     SAVE_NAME VARCHAR NOT NULL,
                     SAVE_PATH VARCHAR,
                     CREATE_AT TIMESTAMP,
                     CONSTRAINT fk_employee_file FOREIGN KEY (EMPLOY_ID)
                         REFERENCES EMPLOYEE (ID)
                         ON DELETE CASCADE
);
--이메일 기록 테이블
CREATE TABLE EMAIL_HISTORY (
                               ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                               EMPLOY_ID BIGINT NOT NULL,
                               EMAIL VARCHAR(255) NOT NULL,
                               SEND_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               FOREIGN KEY (EMPLOY_ID) REFERENCES employee(id) ON DELETE CASCADE

);